project:
  type: website
  output-dir: docs
  preview:
    port: 5896
    browser: true
  render:
    - "index.qmd"
    - "about.qmd"
    - "lab.qmd"
    - "research.qmd"
    - "teaching.qmd"
    - "blog/index.qmd"
    - "blog/**/*.qmd"
    - "404.qmd"
  resources:
    - "content/"
    - "css"
    - "splitkbcompare.html"
    - "static/"

website:
  title: "Home"
  description: "The personal website of Corrado Caudek"
  image: images/ccaudek_photo.jpeg
  site-url: https://ccaudek.github.io/
  favicon: images/favicon.ico
  repo-url: https://github.com/ccaudek/ccaudek.github.io
  search:
    location: navbar
    type: overlay
  back-to-top-navigation: false
  google-analytics: "G-K1F64JCQ7Q"
  open-graph:
    locale: es_ES
    site-name: https://ccaudek.github.io
  navbar:
    left:
      - text: "About"
        href: about.qmd
      - text: "Lab"
        href: lab.qmd
      - text: "Research"
        href: research.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Blog"
        href: blog/index.qmd
  page-footer:
    center:
      - text: |
          Site made with <i class='bi bi-heart-fill'></i>, 
          <a href='https://github.com/ccaudek/' target='_blank'><i class='bi bi-git'></i></a>, 
          and <a href='https://quarto.org/' target='_blank'><img src='https://quarto.org/favicon.png' width=12> quarto</a>
          <br>
          © 2025 Corrado Caudek

format:
  html:
    theme:
      - simplex
      - theme.scss
    mainfont: Palatino
    linkcolor: "#dc2828"
    grid:
      sidebar-width: 300px
      body-width: 723px
      margin-width: 300px
    code-copy: false
    code-fold: true
    lightbox: true
    anchor-sections: false
    link-external-newwindow: true
    date-format: long
    execute: 
      warning: false
      message: false

